name: Release
on:
  push:
    tags:
      - 'V[0-9].[0-9]'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      # Install Node.js and npm
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install Node dependencies
        run: |
          sudo apt update && sudo apt install build-essential -y && npm ci --force

      - name: Generate JavaScript
        run: |
          npm run prod

      # Read the contents of the changelog file
      - name: Read changelog
        id: changelog
        run: echo ::set-output name=contents::$(cat storage/changelog.txt)

      # Create the release on GitHub
      - name: Create Release
        uses: actions/gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: true
          files: |
            app/**
            bootstrap/**
            config/**
            database/**
            public/**
            resources/**
            routes/**
            storage/**
            tests/**
            vendor/**
            .env.example
            artisan
            composer.json
            composer.lock
            package.json
            package-lock.json
            webpack.mix.js

      # Output a message
      - name: Output message
        if: success()
        run: echo "The release was created successfully!"
