name: Release
on:
  push:
    tags:
      - 'V*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      # Install Node.js and npm
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install Node dependencies
        run: |
          sudo apt update && sudo apt install build-essential -y && npm ci --force

      - name: Generate JavaScript
        run: |
          npm run prod
          
      - name: Run Composer
        run: |
          composer install

      # Read the contents of the changelog file
      - name: Read changelog
        id: changelog
        run: echo ::set-output name=contents::$(cat storage/changelog.txt)
        
      - name: Rename env file
        run: mv .env.template .env
        
      - name: Zip Folder
        run: |
          find . \
            -path './.git' -prune -o \
            -path './.github' -prune -o \
            -name '.env.ci' -prune -o \
            -name '.gitattributes' -prune -o \
            -name '.gitignore' -prune -o \
            -name '.eslintrc.json' -prune -o \
            -name '.editorconfig' -prune -o \
            -name '.styleci.yml' -prune -o \
            -name 'phpunit.xml' -prune -o \
            -name 'package-lock.json' -prune -o \
            -name 'package.json' -prune -o \
            -name 'webpack.mix.js' -prune -o \
            -name 'node_modules' -prune -o \
            -path 'resources/js' -prune -o \
            -path 'resources/css' -prune -o \
            -type f -print | zip ${{ github.event.repository.name }}.zip -@

      # Create the release on GitHub
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: true
          files: ${{ github.event.repository.name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
